# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2confl < Formula
  desc "md2confl is a CLI tool to convert the markdown text to confluence wiki format."
  homepage "https://github.com/kentaro-m/md2confl"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/kentaro-m/md2confl/releases/download/v0.4.1/md2confl_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "d421795af18404bb9e2548386ae2f2a4d80c8b94afd9782eb19e614b395c7703"
    end
    if Hardware::CPU.arm?
      url "http://github.com/kentaro-m/md2confl/releases/download/v0.4.1/md2confl_0.4.1_Darwin_arm64.tar.gz"
      sha256 "e69f90a16aa01a2a0afc13f4bb5181986a514d7c761a6d1dee8dc70c0420d44c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/kentaro-m/md2confl/releases/download/v0.4.1/md2confl_0.4.1_Linux_x86_64.tar.gz"
      sha256 "b9721192ff35e5f479fe87ff9826620182071c5773fe0560776cdbf3d79df7dd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/kentaro-m/md2confl/releases/download/v0.4.1/md2confl_0.4.1_Linux_arm64.tar.gz"
      sha256 "9d6d0746edb1ceec348076bc3e49beea6b88355f42ba63cccd2ba32061bb88c7"
    end
  end

  def install
    bin.install "md2confl"
  end

  test do
    system "#{bin}/md2confl --version"
  end
end
